### ISSUE TITLE
Illegal font distribution

### ISSUE THREAD

**Issue by MarcusSterz** [fredrik-hansen/fredrik-hansen#1]
Hello,

I am the designer of the MonoLisa typeface which you offer here for free. Since the EULA clearly states that distribution through third parties is not allowed (not matter if free or not), you are violating the law.
Please take it down as soon as you read this – thank you.

Marcus Sterz

**Comment by fredrik-hansen** [comment]
Apologies, @MarcusSterz - repo is deleted.

**Comment by fredrik-hansen** [comment]
Apologies, @MarcusSterz  - repo is deleted.
